### ISSUE TITLE
Parentheses don't work as expected

### ISSUE THREAD

**Issue by owenversteeg** [hausen/math.diff.js#3]
As the title says. The demo version works with version 1.7.0, so somewhere between 2.4.0 and 1.7.0 math.diff.js broke. I'd assume somewhere around the 2.0 release.

Simple things work, for example: `math.diff(math.parse('e^x'), 'x').toString()`

Slightly more complex things, however, break: `math.diff(math.parse('e^(2*x)'), 'x').toString()` returns "0".

[edit] After realizing that this is only because of parentheses and the addition of ParenthesisNode I renamed the title.

**Comment by owenversteeg** [comment]
Testing that I did just now:
- 1.7.0 works
- 1.7.1 works
- 2.0.0 broken
- 2.4.0 broken
- 2.5.0 broken (latest release, 11 days ago)

[Here are the breaking changes for 2.0.0](http://mathjs.org/history.html#breaking-changes). Seems like the three things that might cause an issue are:
- String input is now converted to numbers by default for all functions.
- Adding two strings will no longer concatenate them, but will convert the strings to numbers and add them.
- The size of Arrays is no longer validated. Matrices will validate this on creation.

**Comment by hausen** [comment]
Thanks for the report. Mathjs versions 2.0.0 and up include the parentheses in the expression tree with a new expression node called "ParenthesisNode." Since my code predated v. 2.0.0, it couldn't handle parenthesized expressions parsed with newer versions of Mathjs.

I have updated the code to just ignore those nodes (they're not needed in an expression tree, after all) and it seems to be working normally with the latest version: `math.diff(math.parse('e^(2*x)'), 'x').toString()` now returns the correct answer. Have you tried any other expressions?

**Comment by owenversteeg** [comment]
Ah, thanks! I did, but they all were caused by the ParenthesisNode bug. Looks like 392d4c0 and 6eb0d50 fixed the problems. Thanks!

**Comment by owenversteeg** [comment]
Oh, never mind, for some reason it still doesn't work. With the latest version (2.5.0) of Math.js and the latest math.diff.js, `math.diff(math.parse('e^(2*x)'), 'x').toString()` still returns 0. 2.0.0 still doesn't work as well.

**Comment by hausen** [comment]
392d4c0 worked in most of the cases, and 6eb0d50 should fix it completely, but it introduced another bug. 01e8530 fixes the "fix".
